Review Suggestions on #9
rishiip/wheel pull request #12
Opened 2022-08-19 05:46 UTC by rishiip

Ref PR - #9

2022-08-19 07:01 UTC, yedhink commented
I will review this PR once https://github.com/rishiip/wheel/pull/9#discussion_r949862101 is answered.

2022-08-22 12:16 UTC, yedhink requested changes
@rishiip Once the following changes are made, please go ahead and do `Squash and Merge`.

2022-08-22 12:16 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/Note.jsx
> +import dayjs from "../../../lib/dayjs";
- First thing, if the relative path becomes too long, then it's better to create an webpack alias for it. Please read: https://www.bigbinary.com/books/learn-rubyonrails-book/setting-up-react-environment#aliases 
- Secondly over here you don't need to import from `lib/dayjs`. That's same as your previous implementation where you had imported the dayjs instance from `constants`. Here import directly from `dayjs` itself. But in the root component, something like `Main.jsx`, add a single import, like `import "lib/dayjs"` for initialization purposes. That's good enough I believe.

2022-08-22 12:16 UTC, yedhink commented on app/javascript/src/lib/dayjs.js
> +export default dayjs;
You don't have to export this instance. `dayjs` instance is global!

2022-08-22 14:21 UTC, rishiip commented on app/javascript/src/components/Dashboard/Notes/Note.jsx
> +import dayjs from "../../../lib/dayjs";
@yedhink - This is done. Thanks a ton for helping me here 🙌🏼

2022-08-22 14:21 UTC, rishiip commented on app/javascript/src/lib/dayjs.js
> +export default dayjs;
This is done. Have a look at latest code.

2022-08-22 14:37 UTC, yedhink commented
@rishiip I am merging this PR now. But moving forward, please read the comments carefully: https://github.com/rishiip/wheel/pull/12#pullrequestreview-1080360066

<img width="775" alt="image" src="https://user-images.githubusercontent.com/31244999/185947946-4f6e9b79-0982-4f24-8654-52e39ccf6fd2.png">

2022-08-22 14:37 UTC, merged