Review Suggestions from #13
rishiip/wheel pull request #15
Opened 2022-08-25 10:54 UTC by rishiip

Review modifications that are suggested on merged PR #13 

![SCR-20220825-mr3](https://user-images.githubusercontent.com/7964257/186646358-c752563d-abf7-4d8d-b27b-9f9f879ea9a3.png)
![SCR-20220825-mrg](https://user-images.githubusercontent.com/7964257/186646374-3d29c83e-169f-4d1b-9756-6d87cf6c293b.png)

2022-08-25 11:11 UTC, yedhink requested changes
@rishiip Few comments.

2022-08-25 11:11 UTC, yedhink commented on app/javascript/src/components/Dashboard/Contacts/constants.jsx
> +import * as Yup from "yup";
yup should be lowercase. [Refer](https://academy.bigbinary.com/learn-react/pages/miscellaneous-tips#:~:text=Before%20we%20move%20ahead%20it%20is%20worth%20pointing%20out%20that%20we%20should%20always%20import%20yup%20in%20lowercase%20as%20it%20is%20imported%20as%20an%20object.%20Only%20classes%20and%20components%20should%20be%20imported%20in%20Pascal%20case.%20And%20constants%20should%20be%20imported%20as%20they%20are%20declared.)

2022-08-25 11:11 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +  tags: Yup.array().required("Tag is required"),
It's always better to also add validation for the inner keys of the objects and arrays.

Refer https://github.com/jquense/yup#getting-started

2022-08-25 15:21 UTC, rishiip commented on app/javascript/src/components/Dashboard/Contacts/constants.jsx
> +import * as Yup from "yup";
This is done. As we're using `Yup` in neetoCRM, previously I thought to use the same here with first letter as capital.

2022-08-25 15:21 UTC, rishiip commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +  tags: Yup.array().required("Tag is required"),
This is done.

2022-08-25 15:22 UTC, rishiip commented
> @rishiip Few comments.

@yedhink - This is done. Ref [commit](https://github.com/rishiip/wheel/pull/15/commits/78f86883628ba85b36b566c6db0438abfbdd7112).

2022-08-25 15:24 UTC, yedhink requested changes
@rishiip _a

2022-08-25 15:24 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +    .required("Tag is required"),
Had you tested this validation from the UI? If no tags are provided does it show an error right now and prevent you from submitting the form as expected?

From my perspective this won't work. But please verify and get back to me.

2022-08-25 16:50 UTC, rishiip commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +    .required("Tag is required"),
@yedhink - 
1. If tags are not provided it's preventing user to submit form as expected. [Have a look.](https://www.loom.com/share/9af7f44f22354455a306729bb410a1d6)
2. Providing `nullable` and `required` to the same entity explanation - [Have a look](https://www.loom.com/share/3a667865efa94141a28c354921411c9b)

2022-08-25 17:38 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +    .required("Tag is required"),
@rishiip https://www.loom.com/share/5d3538062fdd4a42aeaea5275f97c241

2022-08-26 07:23 UTC, rishiip commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +    .required("Tag is required"),
@yedhink - Thanks for pointing this out. This is done. [Have a look at explanation](https://www.loom.com/share/0ec5d459073f490484c7978e48e9466d).

2022-08-26 07:29 UTC, merged